name: loft
version: v4.0.0-beta.10
commands:
  - name: "login"
    usage: "Log into Loft"
    baseArgs: ["login"]
  - name: "token"
    baseArgs: ["platform", "access-key"]
    usage: "Show the current access token for Loft"
  - name: "sleep"
    baseArgs: ["platform", "sleep"]
    usage: "Put a space to sleep"
  - name: "wakeup"
    baseArgs: ["platform", "wakeup"]
    usage: "Wake a sleeping space up"
  - name: "create"
    baseArgs: ["platform", "create"]
    usage: "Create a space or virtual cluster"
  - name: "connect"
    baseArgs: ["platform", "connect"]
    usage: "Connect to a virtual cluster"
  - name: "delete"
    baseArgs: ["platform", "delete"]
    usage: "Delete a space or virtual cluster"
  - name: "get"
    baseArgs: ["platform", "get"]
    usage: "Show a shared secret or Loft user information"
  - name: "spaces"
    baseArgs: ["platform", "list", "spaces"]
    subCommand: "list"
    usage: "List all Loft spaces"
  - name: "secrets"
    baseArgs: ["platform", "list", "secrets"]
    subCommand: "list"
    usage: "List all shared Loft secrets"
  - name: "clusters"
    baseArgs: ["platform", "list", "clusters"]
    subCommand: "list"
    usage: "List all accessible Loft clusters"
  - name: "vclusters"
    baseArgs: ["platform", "list", "vclusters"]
    subCommand: "list"
    usage: "List all accessible virtual clusters"
  - name: "teams"
    baseArgs: ["platform", "list", "teams"]
    subCommand: "list"
    usage: "List Loft teams"
  - name: "vcluster"
    baseArgs: ["platform", "connect", "vcluster"]
    subCommand: "use"
    usage: "Use a virtual cluster"
  - name: "cluster"
    baseArgs: ["platform", "connect", "cluster"]
    subCommand: "use"
    usage: "Use a connected Loft cluster"
  - name: "space"
    baseArgs: ["platform", "connect", "space"]
    subCommand: "use"
    usage: "Use a space"
  - name: "secret"
    baseArgs: ["platform", "set", "secret"]
    subCommand: "set"
    usage: "Write to a shared Loft secret"
vars:
  - name: LOFT_CLUSTER
    baseArgs: ["platform", "get", "cluster"]
  - name: LOFT_USERNAME
    baseArgs: ["platform", "get", "current-user", "--output=name"]
  - name: DEVSPACE_USERNAME
    baseArgs: ["platform", "get", "current-user", "--output=name"]
binaries:
  - os: darwin
    arch: amd64
    path: https://github.com/loft-sh/vcluster/releases/download/v0.20.0/vcluster-darwin-amd64
  - os: darwin
    arch: arm64
    path: https://github.com/loft-sh/vcluster/releases/download/v0.20.0/vcluster-darwin-arm64
  - os: linux
    arch: amd64
    path: https://github.com/loft-sh/vcluster/releases/download/v0.20.0/vcluster-linux-amd64
  - os: linux
    arch: arm64
    path: https://github.com/loft-sh/vcluster/releases/download/v0.20.0/vcluster-linux-arm64
  - os: windows
    arch: amd64
    path: https://github.com/loft-sh/vcluster/releases/download/v0.20.0/vcluster-windows-amd64.exe
