name: loft
version: v2.0.0
commands:
  - name: "login"
    baseArgs: ["login"]
  - name: "token"
    baseArgs: ["token"]
  - name: "sleep"
    baseArgs: ["sleep"]
  - name: "wakeup"
    baseArgs: ["wakeup"]
  - name: "create"
    baseArgs: ["create"]
  - name: "connect"
    baseArgs: ["connect"]
  - name: "delete"
    baseArgs: ["delete"]
  - name: "generate"
    baseArgs: ["generate"]
  - name: "get"
    baseArgs: ["get"]
  - name: "spaces"
    baseArgs: ["list", "spaces"]
    subCommand: "list"
  - name: "secrets"
    baseArgs: ["list", "secrets"]
    subCommand: "list"
  - name: "clusters"
    baseArgs: ["list", "clusters"]
    subCommand: "list"
  - name: "vclusters"
    baseArgs: ["list", "vclusters"]
    subCommand: "list"
  - name: "teams"
    baseArgs: ["list", "teams"]
    subCommand: "list"
  - name: "vcluster"
    baseArgs: ["use", "vcluster"]
    subCommand: "use"
  - name: "cluster"
    baseArgs: ["use", "cluster"]
    subCommand: "use"
  - name: "space"
    baseArgs: ["use", "space"]
    subCommand: "use"
  - name: "secret"
    baseArgs: ["set", "secret"]
    subCommand: "set"
vars:
  - name: LOFT_CLUSTER
    baseArgs: ["vars", "cluster"]
  - name: LOFT_USERNAME
    baseArgs: ["vars", "username"]
binaries:
  - os: darwin
    arch: amd64
    path: https://github.com/loft-sh/devspace-plugin-loft/releases/download/v2.0.0/devspace-plugin-loft-darwin-amd64
  - os: darwin
    arch: arm64
    path: https://github.com/loft-sh/devspace-plugin-loft/releases/download/v2.0.0/devspace-plugin-loft-darwin-arm64
  - os: linux
    arch: amd64
    path: https://github.com/loft-sh/devspace-plugin-loft/releases/download/v2.0.0/devspace-plugin-loft-linux-amd64
  - os: linux
    arch: "386"
    path: https://github.com/loft-sh/devspace-plugin-loft/releases/download/v2.0.0/devspace-plugin-loft-linux-386
  - os: windows
    arch: amd64
    path: https://github.com/loft-sh/devspace-plugin-loft/releases/download/v2.0.0/devspace-plugin-loft-windows-amd64.exe
  - os: windows
    arch: "386"
    path: https://github.com/loft-sh/devspace-plugin-loft/releases/download/v2.0.0/devspace-plugin-loft-windows-386.exe
